### ISSUE TITLE
Translation activity

### ISSUE THREAD

**Issue by LeusMaximus** [js-ru/react-ru#1]
Привет. Есть вопрос по-поводу перевода документации. Увидел в [этом разделе](https://github.com/js-ru/react-ru#translation) ссылку на ресурс, где ведутся работы по переводу документации на разные языки. Перевод на русский там тоже начат. Может быть есть смысл объединиться с теми, кто делает перевод там?

**Comment by lex111** [comment]
Привет, извините за доооолгий ответ.

Сейчас сообщество React предоставило возможность сделать официальный перевод, поэтому  в самом разгаре официальный русский перевод - https://github.com/reactjs/ru.reactjs.org
Crowdin использовался скорее как эксперимент, через этот сервис что-то переведено на русский, но очень мало, но этим можно воспользоваться в новом переводе.

Кстати, если хотите, будем рады, если присоединитесь, любая помощь приветствуется.

**Comment by lex111** [comment]
Приветствую @4enki, @dimktsoy, @vvscode, @Aswiz, @Zirochkaa, @Zirochkaa, @RinatValiullov :hand: 

Этот репозиторий больше не будет поддерживаться, поскольку команда React предоставила возможность работы над официальным переводом документации, к участию (или лайкам :star: ), которой я вас призываю.

Спасибо за внимание, и извините за такой "апдейт" :)

[Официальный русский перевод документации React](https://github.com/reactjs/ru.reactjs.org)
